#!/bin/bash
# Basic interface to https://quedia.tv


########## HELPER FUNCTIONS ###########
usage() {
	echo 'qdl
	help
	login
	latest [n]
	search <str>
	eps <series_id>
	dl [-d <outputdir>] <ep_id>+'
}


missing_arg_error() {
	echo "Error: \""$1"\" requires a non-empty option argument." >&2 && exit 1
}


cookiejar_assert_ok() {
	[[ ! -r "${cookiejar}" ]] && { echo "Error: cookiejar ${cookiejar} does not exist or cannot be read by current user. This is expected if you have never logged in." >&2; exit 1; }
}


json_status_assert_ok() {
	[[ "$(jq '.status == "error"' <<< "$1")" == 'true' ]] && { echo 'Error. Your session probably expired. Try logging in again.' >&2; exit 1; }
}


http_status_assert_ok() {
	local status="$(sed -n '1s/HTTP\/1.1 \(...\).*/\1/p' <<< "$1")"
	case "${status}" in
		"404")
			echo "Error: file not found. Please check ID is correct." >&2
			exit 1
			;;
		"403")
			echo "Error: unauthorized. Your session probably expired. Try logging in again." >&2
			exit 1
			;;
		"302")
			# success
			;;
		*)
			echo "Error: ${status}." >&2
			exit 1
			;;
	esac
}


number_assert_ok() {
	local regex='[[:digit:]]+'
	[[ ! "$1" =~ $regex ]] && { echo 'Error: argument should be a number.' >&2; exit 1; }
	[[ "$1" -lt 1 ]] && { echo 'Error: number should be greater than 0.' >&2; exit 1; }
}


quedia_request() {
	if [[ -n "$2" ]]; then
		curl -s -H "Accept: application/json" -H "Content-Type: application/json" -b "${cookiejar}" --data-raw "$2" "https://quedia.tv/api/$1"
	else
		curl -s -H "Accept: application/json" -H "Content-Type: application/json" -b "${cookiejar}" "https://quedia.tv/api/$1"
	fi
}


url_decode() {
	printf '%b' "${1//%/\\x}"
}


jq_print_get_series() {
	jq -r '.response[] as $items | ("> " + ($items.id | tostring) + " " + $items.name + ": " + $items.description)' <<< "$1"
}
#######################################


# check dependencies
command -v jq >/dev/null || { echo "Error: program jq not found." >&2; exit 1; }
command -v curl >/dev/null || { echo "Error: program curl not found." >&2; exit 1; }

# check argcount
[[ "$#" -lt 1 ]] && { usage; exit 1; }

# cookiejar path
user_data_prefix="${XDG_DATA_HOME:-${HOME}/.local/share}"
mkdir -p "${user_data_prefix}/quedia-dl"
cookiejar="${user_data_prefix}/quedia-dl/cookiejar"


while [[ -n "$1" ]]; do
	case "$1" in
		'help')
			usage
			exit
			;;
		'login')
			read -p "Username: " -r username
			read -p "Password: " -s -r password
			echo
			login_payload="$(jq -n -aRc --arg username "${username}" --arg "password" "${password}" '{username: $username, password: $password}')"
			if [[ "$(curl -s -H "Accept: application/json" -H "Content-Type: application/json" --data-raw "${login_payload}" -c "${cookiejar}" 'https://quedia.tv/api/profile/login' | jq '.status == "ok"')" == 'true' ]]; then
				chmod 600 "${cookiejar}"
				echo 'Login successful.' >&2
			else
				echo 'Error. Please double check your credentials.' >&2
				rm -f "${cookiejar}"
				exit 1
			fi
			;;
		'latest')
			cookiejar_assert_ok
			latest_payload='{"limit":0}'
			[[ -n "$2" ]] && { number_assert_ok "$2"; latest_payload="{\"limit\":$2}"; shift; }
			json_reply="$(quedia_request "media/get_series" "${latest_payload}")"
			json_status_assert_ok "${json_reply}"
			jq_print_get_series "${json_reply}"
			;;
		'search')
			if [[ -n "$2" ]]; then
				cookiejar_assert_ok
				search_payload="$(jq -n -aRc --arg str "$2" '{search: $str}')"
				json_reply="$(quedia_request "media/get_series" "${search_payload}")"
				json_status_assert_ok "${json_reply}"
				jq_print_get_series "${json_reply}"
				shift
			else
				missing_arg_error 'search'
			fi
			;;
		'eps')
			if [[ -n "$2" ]]; then
				cookiejar_assert_ok
				number_assert_ok "$2"
				json_reply="$(quedia_request "media/get_series" "{\"id\":$2,\"depth\":3}")"
				json_status_assert_ok
				jq -r '.response[].seasons[].episodes[].signatures[] as $items | ($items.uid + " " + $items.filename)' <<< "${json_reply}"
				shift
			else
				missing_arg_error 'eps'
			fi
			;;
		'dl')
			outputdir='.'
			if [[ "$2" == '-d' ]]; then
				[[ ! -n "$3" ]] && missing_arg_error '-d'
				outputdir="$3"
				shift; shift
			fi
			[[ ! -n "$2" ]] && missing_arg_error 'dl'
			cookiejar_assert_ok
			while [[ -n "$2" ]]; do
				reply="$(curl -si -b "${cookiejar}" "https://quedia.tv/api/storage/get_download_link/$2")"
				http_status_assert_ok "${reply}"
				url="https://quedia.tv$(sed -n 's/Location: \(.*\)/\1/p' <<< "${reply}")"
				url="${url%$'\r'}"
				filename="$(url_decode "${url##*/}")"
				echo "Downloading ${outputdir}/${filename}"
 				curl -o "${outputdir}/${filename}" -b "${cookiejar}" "${url}"
				shift
			done
			;;
		*)
			usage
			exit 1
			;;
	esac
	shift
done

exit 0
